#!/system/bin/sh
# MTK_AI Engine – Bypass Active (Run All, Skip Failures)
export LD_LIBRARY_PATH=/data/adb/modules/MTK_AI/lib64:$LD_LIBRARY_PATH

# Prevent multiple instances
pidof bypass_active >/dev/null 2>&1 && exit 0
exec /data/adb/modules/MTK_AI/MTK_AI/AI_MODE/gaming_mode/bypass_active &
